{% set name = "nap-plot-tools" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0429875d25c829ed37ef644fce965591fad8f2e617f8623c6ed78c9c2b3aa53a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - cmap
    - numpy
    - python >={{ python_min }}
    - qtpy
    - deprecated
    - matplotlib

test:
  imports:
    - nap_plot_tools
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/nap-plot-tools
  summary: A NAPari PLOTter TOOLbar and tools for additional functionalities.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/zoccoler/nap-plot-tools

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - zoccoler
